language: node_js
node_js:
  - 0.10
install:
  - sudo $(which npm) install -g mocha
  - sudo $(which npm) install
  - sudo $(which npm) install -g bower
  - bower install
  - sudo $(which npm) install -g gulp
  - gulp build
